safe:        false
port:        4000
baseurl:     /levelup-website
source:      .
destination: ./_site
plugins:     ./_plugins
permalink:   date

exclude: [config.ru, Gemfile, Gemfile.lock, Procfile, Rakefile, vendor]

sass:
    syntax: scss
    style:  compressed
